name: Build and Release

on:
  push:
    branches:
      - main
      - feat/release-cicd

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Semantic Release
        run: npm install semantic-release @semantic-release/git @semantic-release/changelog

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release
          echo "::set-output name=version::$(cat package.json | jq -r '.version')"

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
    
      - name: Print Go version
        run: go version

      - name: Build for Linux
        run: make build_linux
        
      - name: Create tar package
        run: tar -czvf go-proxy-${{ steps.semantic.outputs.version }}.tar.gz path/to/your/binary
        
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.repository.releases_url }}
          asset_path: ./go-proxy-${{ steps.semantic.outputs.version }}.tar.gz
          asset_name: go-proxy-${{ steps.semantic.outputs.version }}.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}