name: Build and Release

on:
  push:
    branches-ignore:
      - main  # Exclude the main branch
    tags-ignore:
      - '*'  # Exclude all tags

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.22"
    
      - name: Print Go version
        run: go version

      - name: Build for Linux
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o go-proxy ./main.go
